worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is_testing: true

server-port: 8080

# realworld_service_db_1 is the service name + _ + filename of the db_1.sql
dbconnection: 'postgresql://testsuite@localhost:15433/realworld_service_db_1'
